name: viecnow
description: Việc làm thêm cho sinh viên Đà Nẵng

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  image_picker: ^1.0.7
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0  
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
